name: CSIswim
favicon: null
layout_spectrum: 0.5026
typography_spectrum: 0.924599721794948
title: The Future of Swimming in Cleveland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#000000'
    - '#00598e'
    - '#856966'
    - '#4aa6b1'
  brandStrength: 0.5850885252002627
  lightness: 0.3010078314691782
  saturation: 0.09853934473358095
  rhythmicContrast: 0.5066183269955218
purpose: []
